# Generated by Django 3.2.3 on 2021-05-17 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата')),
                ('match_name', models.CharField(max_length=100, verbose_name='Название')),
                ('match_count', models.SmallIntegerField(default=100, verbose_name='Количество зрителей')),
                ('match_distance', models.FloatField(verbose_name='Расстояние')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Maтчи',
                'ordering': ['match_date'],
            },
        ),
    ]
